

namespace Puzzle89
{
	public static class Data
	{
		// Your data properties and methods go here

		public static readonly Dictionary<int, string> EpisodeTitles = new()
		{
			{ 88, "Collapsible Panels" },
			{ 87, "What a Drag!" },
			{ 86, "Unexpected 404" },
			{ 85, "Voice Control" },
			{ 84, "Breadcrumbs Components" },
			{ 83, "Breadcrumbs" },
			{ 82, "State Laws" },
			{ 81, "Dashboard Dilemma" },
			{ 80, "Hidden JavaScript Issue" },
			{ 79, "Are We Connected Yet?" },
			{ 78, "Why So Slow?" },
			{ 77, "Unhelpful Errors" },
			{ 76, "Environments for Everyone!" },
			{ 75, "Instant InputText" },
			{ 74, "Canceling Navigation" },
			{ 73, "Referring to Refs" },
			{ 72, "Dynamic Bootstrap" },
			{ 71, "Dirty Models" },
			{ 70, "Playwrighter's Block" },
			{ 69, "QuickGrid of All Sorts" },
			{ 68, "Raiders of the Lost HTTP Headers" },
			{ 67, "Date Input Woes!" },
			{ 66, "The Key Vault is Locked!" },
			{ 65, "Exception Impossible!" },
			{ 64, "A Phantom Menace?" },
			{ 63, "There Can Only Be One" },
			{ 62, "Look Ma! No Magic Strings!" },
			{ 61, "Wrangling Resources" },
			{ 60, "Happy Holidays!" },
			{ 59, "Coding for Dollars" },
			{ 58, "Multi-Tenant State" },
			{ 57, "Loony Localizations" },
			{ 56, "The Case of the Curious Counter" },
			{ 55, "Coding the Code-Behind" },
			{ 54, "Time for Timer!" },
			{ 53, "Navigation Problems" },
			{ 52, "Who?" },
			{ 51, "Values That Bind" },
			{ 50, "Clicky No Worky!" },
			{ 49, "I Feel Invalidated!" },
			{ 48, "Virtually Nothing" },
			{ 47, "Production Challenge" },
			{ 46, "Injection Rejection!" },
			{ 45, "Where'd my NavLink Go?" },
			{ 44, "No RCL Protection!" },
			{ 43, "Virtually Overworked" },
			{ 42, "Impossible CSS" },
			{ 41, "Show Me The Email!" },
			{ 40, "I Want my QR Code!" },
			{ 39, "What The Form!" },
			{ 38, "Link the Weather" },
			{ 37, "Minimal API Issue" },
			{ 36, "Can't Log Out!" },
			{ 35, "Encrypt This!" },
			{ 34, "Static Search" },
			{ 33, "The Components that Bind" },
			{ 32, "Updating Parameters" },
			{ 31, "Re-use This!" },
			{ 30, "Where's The Layout?" },
			{ 29, "A Pre-Render Bender?" },
			{ 28, "Where's the HTML?" },
			{ 27, "Click Once, That's It!" },
			{ 26, "From RCL to Routable Page" },
			{ 25, "ButtonNumber++" },
			{ 24, "Let us Stand Alone" },
			{ 23, "Forge Ahead!" },
			{ 22, "Icon Not Find Icons!" },
			{ 21, "Bungle a Bundle" },
			{ 20, "It's a 404 World" },
			{ 19, "To Layout or Not Layout" },
			{ 18, "Where's the Config?" },
			{ 17, "Whether or Not" },
			{ 16, "No Message for You!" },
			{ 15, "Unexpected Behavior" },
			{ 14, "Simple App Doesn't Work" },
			{ 13, "Upgrade This App!" },
			{ 12, "Build a Better Background Service" },
			{ 11, "Build a Better State Bag" },
			{ 10, "Stop the Rendering" },
			{ 9, "A Matter of Focus" },
			{ 8, "A Printing Puzzle" },
			{ 7, "A Parameter Problem #2" },
			{ 6, "A Parameter Problem" },
			{ 5, "Localization Woes" },
			{ 4, "Lazy Not Loading!" },
			{ 3, "JavaScript Calling!" },
			{ 2, "Got JavaScript?" },
			{ 1, "Introducing The Blazor Puzzle" }
		};
	}
}